version: '3'

services:
    rocketchat_bot_wakeonlan:
        build: ./
        image: rocketchat_bot_wakeonlan
        network_mode: host
        restart: always
        volumes:
            - "./:/usr/src/app/"
        environment:
            - HOST=<HOSTNAME_HERE>
            - USER=<BOT_USERNAME_HERE>
            - PASS=<BOT_PASSWORD_HERE>
